[config]
schemaVersion = "1.0.3"

[general]
repository = "https://github.com/redystum/LC-TheKirby"

[package]
description = "I think i have seen a Kirby somewhere..."
websiteUrl = "https://github.com/redystum/LC-TheKirby"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.16.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/Redystum.TheKirby.dll"
target = "plugins/Redystum.TheKirby/"

[[build.copy]]
source = "../../UnityProject/AssetBundles/StandaloneWindows/modassetsthekirby"
target = "plugins/Redystum.TheKirby/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "monsters", "mods", ]